---
name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{Secrets.EC2_KEY}}
          REMOTE_HOST: ${{Secrets.EC2_HOST}}
          REMOTE_USER: ${{Secrets.EC2_USER}}
      - name: Execute SSH commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo npm install
            sudo npm install pm2 -g
            sudo pm2 start index.js